# =====================================================================
# NATS Server Configuration — Development / Test Mode
# JetStream enabled, no strict auth (untuk kemudahan testing)
# =====================================================================

port: 4222
http_port: 8222
server_name: iot-nats

jetstream {
  store_dir: /data/jetstream
  max_memory_store: 128MB
  max_file_store: 1GB
}

debug: false
trace: false
logtime: true
